spring.application.name=api-gateway
server.port=8080

# ===== Eureka =====
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

# ===== Routes =====

# Auth Service
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/users/**

# Catalog Service
spring.cloud.gateway.server.webflux.routes[1].id=catalog-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://CATALOG-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/categories/**

# Borrow Service
spring.cloud.gateway.server.webflux.routes[2].id=borrow-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://BORROW-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/borrow/**

# Book Service
spring.cloud.gateway.server.webflux.routes[3].id=book-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://BOOK-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/books/**

# ===== CORS =====
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:3000
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allow-credentials=true
spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true


# ===== Exclude Security =====
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration,org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration