spring.application.name=eureka-server
server.port=8761

# Eureka server: don't register itself & don't fetch registry
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=eureka-server